### ISSUE TITLE
getting error on windows

### ISSUE THREAD

**Issue by askfriends** [aayush2718/Auto-Link-Bypasser#4]
im getting following error on windows, will u fix it?

```
Traceback (most recent call last):
  File "C:\Users\USERNAME\Documents\Auto-Link-Bypasser\bypass.py", line 25, in <module>
    url = sys.argv[1]
IndexError: list index out of range
```

**Comment by archelaus** [comment]
You need to call `bypass.py` with an argument, _e.g.:_
`bypass.py <link>`

**Comment by askfriends** [comment]
> You need to call `bypass.py` with an argument, _e.g.:_ `bypass.py <link>`

yeah that worked. Thanks
